'Program : Music (Afsane)
'Programer : FARZAD BADILI (FDB@bigfoot.com)
'http://www.inernettrash.com/users/fdb/


REM afsane
b:
READ A$: PLAY "t150"
IF A$ = "end" THEN END
IF A$ = "stop" AND A = 0 THEN A = 1: GOTO b
IF A$ = "stop" AND A = 1 THEN STOP
IF A$ = "again" AND b = 1 THEN GOTO b
IF A$ = "again" AND b = 0 THEN b = 1: RESTORE: GOTO b
PLAY A$: GOTO b
DATA o3l2g.,e.,g.,e.,l4p4eg,o4l2c.,l4p4dc,o3bag
DATA o3l2fl4e,l2d.,l2f.,d.,f.,d.,l4p4df,l2b.
DATA o4p4l4co3b,agf,l2el4d,l2c.
DATA o3l2g.,e.,g.,e.,l4p4eg,o4l2c.l4p4dc,o3bag
DATA o3l2fl4e,l2d.,l2f.,d.,f.,d.,l4p4df,l2b.
DATA o4p4l4co3b,agf,l2el4d,l2c.
DATA l4o3p4ce,l2al4g,p4eg,l2o4dl4c
DATA l4o3p4go4c,l8egfedc,l8o3bo4dco3bag
DATA o3l2fl4e,l2d.,l4p4o2bo3d,l2gl4f,l4p4df,l2bl4a
DATA o2l4p4fg,l8abo3def,gabo4cddf,l2el8ded,l2c.,end

