'Program : Music (Joojeh)
'Programer : FARZAD BADILI(FDB@bigfoot.com)
'http://www.inernettrash.com/users/fdb/ 

REM joojeh
p1:
READ score$
IF score$ = "end" THEN END
PLAY score$
GOTO p1
END
p2:
REM ***************************** data section *****************************
DATA mlt120
DATA o3l8a#p8a#a#,l16a#aa#o4c#,o3A#al8aa,p8aal16a
DATA gaa#a,gl8gl4a#l16a#,al8a#l16a#a,a#o4edc#
DATA o3a#al4al8a,al16aga,a#agg,f#l8f#f#f#
DATA f#ef#e,al2ddl8d,p8dp8e,f#edd
DATA ddde,f#ede,eeee,l16f#gl8f#e
DATA el16eal8g,f#el16ef#,l8eddp8,dp8ef#
DATA eddd,ddef#,edee,eeel16f#
DATA gl8f#ee,l16eal8gf#,el16ef#l8e,df#ga
DATA aal16aa#,aggf#,l8gaa#o4l16c#,o3a#l8al16aa#
DATA agl8af#,gaaa,l16aa#ag,gf#l8ga
DATA a#o4l16c#o3a#l8a,l16aa#ag,l8al4a#l8a#a#,l16a#aa#o4c#
DATA o3a#al8al4a,l8aal16ag,aa#ag,l8gl4a#l8a#a#
DATA l16a#aa#o4e,dc#o3a#a,l4al8aal16a,gaa#a
DATA gl8gf#f#,f#f#ef#,eddp8,dp8d,end





