'Program : Music (Lashkar Saheb Zaman)
'Programer : FARZAD BADILI(FDB@bigfoot.com)
'http://www.inernettrash.com/users/fdb/

REM lashkar saheb zaman
b:
READ A$: PLAY "t150"
IF A$ = "end" THEN END
IF A$ = "STOP" AND A = 0 THEN A = 1: GOTO b
IF A$ = "stop" AND A = 1 THEN STOP
IF A$ = "again" AND b = 1 THEN GOTO b
IF A$ = "again" AND b = 0 THEN b = 1: RESTORE: GOTO b
PLAY A$: GOTO b
DATA o3l4aab-,aaab-,ab-o4co3b-,gab-a
DATA o3l4aab-,aaab-,ab-o4co3b-,gab-a
DATA o4l4ddde,fedc,cco3ab-,o4dco3b-a
DATA o4l4ddde,fedc,cco3ab-,o4dco3b-a
DATA o4l2do3l8ab-o4c,l2dl8o3ab-o4c
DATA o4l4defg,l1a,end


