'Program : Music (Micheal Strogoff)
'Programer : FARZAD BADILI(FDB@bigfoot.com)
'http://www.inernettrash.com/users/fdb/

REM micheal strogoff
b:
READ A$: PLAY "t150"
IF A$ = "end" THEN END
IF A$ = "stop" AND A = 0 THEN A = 1: GOTO b
IF A$ = "stop" AND A = 1 THEN STOP
IF A$ = "again" AND b = 1 THEN GOTO b
IF A$ = "again" AND b = 0 THEN b = 1: RESTORE c: GOTO b
PLAY A$: GOTO b
DATA o4l2e.l8dc,l2c.l8o3ba,l2a.o4l4c,o3l1b
c:
DATA o3l8p8bo4cdeo3bo4co3a,l4g+.o4l8fl2e
DATA o3l8p8bo4cdedco3b,l4a.o4l8fl2e
DATA o4l8p8aag+bag+a,l4f.l8dl2d,l8p8aag+bag+a
DATA o5l4c.l8o4al2a,l4ao5co4ba,l1b
DATA o3l8p8bo4cdeo3bo4co3a,l4g+.o4l8fl2e
DATA o3l8p8bo4cdedco3b,l4a.o4l8fl2e
DATA o4l8p8aag+bag+a,l4f.l8dl2d,l8p8aag+bag+a
DATA o5l4c.l8o4al2a,l4o4b.l8g+l2g,l1a,stop
DATA o4l4p4ea.l8g,g.l8fl2f,l4p4l8gabagf,l4f.l8el2e
DATA o4l4p4cf.l8e,l4e.l8d+l2d,l4p4l8efedo3bo4c,o3l4b.l8al2a
DATA o4l4ea.l8g,g.l8fl2f,l4p4l8gabagf,l4f.l8el2e
DATA o4l4p4cf.l8e,l4e.l8d+l2d,l4p4l8efedo3bo4c
DATA o3l4b.l8al2a,again,end

