'Program : Music (Peivasteh)
'Programer : FARZAD BADILI(FDB@bigfoot.com)
'http://www.inernettrash.com/users/fdb/

PLAY "o4l4f+.f+.l8bal4ep4l8co3ao4edl2f"
PLAY "o4l4f+f+.l8bal4ep4l8co3ao4edl2f"
PLAY "o4l8cl16ccl8dl16ddl8el16eel8dl16dd"
PLAY "o4l4p4co3ap4o4co3ap4o4cep4ae"
PLAY "o4l4mle.l8eo3abo4l4c.c."
PLAY "t52 o3l8d.l16fl8ab-l2al8b-o4co3b-gl2a"
PLAY "o3l4cdefg"
PLAY "o3l2bl4a.l8gl4fel2dl4el8gfl4g.l8e"
PLAY "o3l8eal4o4c.l8o3al1bp4l8bo4cl4d.l8o3bo4l1c"
PLAY "o5l4c.l8o4al2mlal4ao5l4co4bal1b"
PLAY "o5l4c.l8o4al2mnal4b.g+l2gl1a"
PLAY "o5l4c.l8o4al2mlal4ao5l4co4bal1b"
PLAY "o5l4c.l8o4al2mnal4b.g+l2gl1a"
PLAY "o3l8ddl2ab - o4co3l2el8fel2dl8dd"
PLAY "o4l2dl8efl4eo3l8b-al4a"
PLAY "o3l2ab-o4co3l2el8fel2dl8dd"
PLAY "o4l2dl8efl4eo3l8b-al4a"
PLAY "o4l4p4eedl2ccl4dedcl2ee"

