'Program : Music (Shadi)
'Programer : FARZAD BADILI(FDB@bigfoot.com)
'http://www.inernettrash.com/users/fdb/

REM shadi
b:
READ A$: PLAY "t150"
IF A$ = "end" THEN END
IF A$ = "stop" AND A = 0 THEN A = 1: GOTO b
IF A$ = "stop" AND A = 1 THEN STOP
IF A$ = "again" AND b = 1 THEN GOTO b
IF A$ = "again" AND b = 0 THEN b = 1: RESTORE: GOTO b
PLAY A$: GOTO b
DATA o3l2al4ao4e,l4p4co3ba,aaao4e,p4co3ba
DATA o3l2al4ao4e,l4p4co3ba,aaao4e,p4co3ba
DATA o4l2el4ee,p4ddc,cdee,p4ddc
DATA o4l2el4ee,p4ddc,cdee,p4ddc
DATA o4l2dl4dd,p4co3ba,abo4cd,p4co3ba
DATA o4l2dl4dd,p4co3ba,abo4cd,p4co3ba
DATA o4l2cl4cc,p4edc,l2cl4cc,p4edc
DATA o4l2dl4dd,l4co3ba,abo4cd,p4co3ba
DATA o4l2dl4dd,l4co3ba,abo4cd,p4co3ba,end

