'Program : Music (Tavallod Mobarak)
'Programer : FARZAD BADILI(FDB@bigfoot.com)
'http://www.inernettrash.com/users/fdb/

b:
READ A$: PLAY "t150"
IF A$ = "end" THEN END
IF A$ = "stop" AND A = 0 THEN A = 1: GOTO b
IF A$ = "stop" AND A = 1 THEN STOP
IF A$ = "again" AND b = 1 THEN GOTO b
IF A$ = "again" AND b = 0 THEN b = 1: RESTORE: GOTO b
PLAY A$: GOTO b
DATA o3l8gl4g
DATA o4l4c.o3l8gl4g,o4l4c.o3l8gl4g,o4l4cl8co3bl4a,b.l8gl4g,b.l8gl4g
DATA o3l4b.l8gl4g,al8gal4b,o4c.o3l8gl4g
DATA o4l4c.o3l8gl4g,o4l4c.o3l8gl4g,o4l4cl8co3bl4a,b.l8gl4g,b.l8gl4g
DATA o3l4b.l8gl4g,al8gal4b,o4c.,stop
DATA o4l8gl4aal8gfl4e,d.l8dl4e,el8del4d,c.l8dl4a
DATA o4l4al8gfl4e,d.l8dl4e,el8del4d,c.,again,end

