'Program : Music (Yek Gol Sayeh Chaman)
'Programer : FARZAD BADILI(FDB@bigfoot.com)
'http://www.inernettrash.com/users/fdb/

REM yek gol sayeh chaman
b:
READ A$: PLAY "t150"
IF A$ = "end" THEN END
IF A$ = "stop" AND A = 0 THEN A = 1: GOTO b
IF A$ = "stop" AND A = 1 THEN STOP
IF A$ = "again" AND b = 1 THEN GOTO b
IF A$ = "again" AND b = 0 THEN b = 1: RESTORE: GOTO b
PLAY A$: GOTO b
DATA o3l4p4eee,gg,fd,ggfd
DATA o3l4p4edc,l2de,p4l4edc,l2o2aa
DATA o3l4p4eee,gg,fd,ggfd
DATA o3l4p4edc,l2de,p4l4edc,l2o2aa
DATA o3l4co2bo3co2b,p4o3cl2d
DATA o3l4co2bo3cd,co2bl2a
DATA o3l4co2bo3co2b,p4o3cl2d
DATA o3l4co2bo3cd,co2bl2a,again,end

